analyze_competitors_task:
  description: >
        Conduct comprehensive competitive analysis for {company_name}.
        
        Company: {company_name}
        Description: {company_description}
        Industry: {industry}
        
        Research and analyze:
        1. Direct competitors (minimum 5 companies)
        2. Indirect competitors and alternatives
        3. Competitive positioning and differentiation
        4. Pricing strategies and business models
        5. Market gaps and opportunities
        
        For each competitor, provide:
        - Company name and website
        - Target market and positioning
        - Key products/services
        - Pricing model (if available)
        - Strengths and weaknesses
        - Recent developments
        
        Output a comprehensive competitive landscape analysis with strategic recommendations.
  expected_output: >
    Detailed competitive analysis with specific competitors, positioning, and strategic recommendations
  agent: market_intelligence_agent

develop_business_strategy_task:
  description: >
        Develop comprehensive business strategy for {company_name}.
        
        Company: {company_name}
        Description: {company_description}
        Target Market: {target_market}
        
        Create detailed strategy covering:
        
        1. VALUE PROPOSITION DESIGN
        - Primary value proposition statement
        - Unique selling points and differentiators
        - Value proposition for each customer segment
        - Proof points and validation
        
        2. GO-TO-MARKET STRATEGY
        - Customer acquisition channels
        - Sales process and methodology
        - Marketing strategy and messaging
        - Launch timeline and milestones
        
        3. PARTNERSHIP STRATEGY
        - Strategic partnership opportunities
        - Channel partner possibilities
        - Technology integration partners
        - Partnership development approach
        
        4. CUSTOMER RELATIONSHIP STRATEGY
        - Customer onboarding process
        - Customer success and retention
        - Community building approach
        - Customer feedback loops
        
        Research successful companies in similar markets for best practices and strategic approaches.
        Provide specific, actionable recommendations with implementation guidance.
  expected_output: >
    Comprehensive business strategy with value propositions, go-to-market plan, and partnership strategy
  agent: business_strategy_agent

analyze_business_financials_task:
  description: >
        Conduct comprehensive financial analysis for {company_name}.
        
        Company: {company_name}
        Description: {company_description}
        Business Model: {business_model}
        
        Analyze and design:
        
        1. REVENUE MODEL DESIGN
        - Appropriate pricing models (subscription, freemium, usage-based, etc.)
        - Pricing tiers and feature packaging
        - Revenue stream diversification opportunities
        - Pricing strategy benchmarks from similar companies
        
        2. UNIT ECONOMICS ANALYSIS
        - Customer acquisition cost (CAC) estimates
        - Customer lifetime value (LTV) projections
        - LTV:CAC ratios and payback periods
        - Gross margin and contribution margin analysis
        
        3. COST STRUCTURE ANALYSIS
        - Fixed vs variable cost breakdown
        - Technology and infrastructure costs
        - Personnel and operational costs
        - Cost optimization opportunities
        
        4. FINANCIAL PROJECTIONS
        - 3-year revenue projections
        - Cash flow analysis and burn rate
        - Break-even analysis and timeline
        - Funding requirements and milestones
        
        5. KEY RESOURCES & ACTIVITIES
        - Critical resources needed for operations
        - Key activities that drive value creation
        - Resource allocation priorities
        - Operational efficiency metrics
        
        Research industry benchmarks and best practices for similar business models.
        Provide specific recommendations for optimizing financial performance.
  expected_output: >
    Comprehensive financial analysis with revenue model, unit economics, cost structure, and projections
  agent: financial_analysis_agent